const countriesManifest: { [key: string]: any } = {
    germany: require('./germany.webp'),
    netherlands: require('./netherlands.webp'),
    nz: require('./nz.webp'),
    png: require('./png.webp'),
    russia: require('./russia.webp'),
    spain: require('./spain.webp'),
    sweden: require('./sweden.webp'),
    uk: require('./uk.webp'),
    usa: require('./usa.webp'),
    philipines: require('./philipines.webp'),
    switzerland: require('./switzerland.webp'),
    ethiopia: require('./ethiopia.webp'),
    hk: require('./hk.webp'),
    afghanistan: require('../afghanistan.webp'),
    colombia2: require('./colombia_optimized_reduced2.webp'),
    finland: require('./finland.webp'),
    france: require('./france_optimized.webp'),
    india: require('./india2_optimized.webp'),
    japan_lunch: require('./japan_lunch_optimized.webp'),
    saudi: require('./saudi_optimized.webp'),
    south_sudan: require('./south_sudan_optimized.webp'),
    srilanka: require('./srilanka_optimized.webp'),
};

export default countriesManifest;