const countriesManifest: { [key: string]: any } = {
    germany: require('./germany.webp'),
    netherlands: require('./netherlands.webp'),
    nz: require('./nz.webp'),
    png: require('./png.webp'),
    russia: require('./russia.webp'),
    spain: require('./spain.webp'),
    sweden: require('./sweden.webp'),
    usa: require('./usa.webp'),
    philipines: require('./philipines.webp'),
    switzerland: require('./switzerland.webp'),
    ethiopia: require('./ethiopia.webp'),
    hk: require('./hk.webp'),
    afghanistan: require('../afghanistan.webp'),
    colombia: require('./colombia_optimized_reduced2.webp'),
    finland: require('./finland.webp'),
    france: require('./france_optimized.webp'),
    india: require('./india2_optimized.webp'),
    japan_lunch: require('./japan_lunch_optimized.webp'),
    saudi: require('./saudi_optimized.webp'),
    south_sudan: require('./south_sudan_optimized.webp'),
    srilanka: require('./srilanka_optimized.webp'),
    laos: require('./laos.webp'),
    malaysia: require('./malaysia.webp'),
    iceland: require('./iceland.webp'),
    mongolia: require('./mongolia.webp'),
    nz_maori: require('./nz_maori.webp'),
    taiwan: require('./taiwan.webp'),
    norway: require('./norway.webp'),
    uzbekistan: require('./uzbekistan.webp'),
    uk: require('./uk.webp'),
    australia: require('./australia.webp'),
    argentina: require('./argentina.webp'),
    cuba: require('./cuba.webp'),
    iran: require('./iran.webp'),
    belgium: require('./belgium.webp'),
    mexico: require('./mexico.webp'),
    italy: require('./italy.webp'),
    china: require('./china.webp'),
    // thailand: require('./thailand.webp'),
    // turkey: require('./turkey.webp'),
    // vietnam: require('./vietnam.webp'),
    // zimbabwe: require('./zimbabwe.webp'),
    // zambia: require('./zambia.webp'),
    // zimbabwe: require('./zimbabwe.webp'),
};

export default countriesManifest;